### ISSUE TITLE
ram Allocation issue

### ISSUE THREAD

**Issue by esiw2** [Offline-CheatBreaker/Client#22]
i allocate 16gb ram on the launcher when i go into the game 
![2022-02-03_23 04 16](https://user-images.githubusercontent.com/98990791/152445140-ecf2b85f-3146-496a-a907-2fd14d571065.png)
it only allocates 6% 
but on lunar client it allocates 100%
![2022-02-03_23 17 20](https://user-images.githubusercontent.com/98990791/152445482-ce37ca87-c2ec-457d-b8ef-f149dbc0be42.png)
windows 10 
both 1.8.9 and 1.7.10 have this issue

**Comment by ShonP40** [comment]
Not an issue
The client will only use what it needs

Not to mention that Minecraft 1.7-1.8 basically never uses more than ~4GB of RAM

**Comment by Tellinq** [comment]
To add, Lunar Client does not actually allocate RAM properly due to not setting the Heap Size. 
The first screenshot is intentional, and is a good thing.

Also, please only allocate less than 4 GB, preferably 3.3 GB. Just like Shon said, Minecraft 1.7 and 1.8 do not use more than 4 GB unless you are using an intensive modpack, which is not the case here.
